### ISSUE TITLE
Create: Integration for rxJS

### ISSUE THREAD

**Issue by frank-dspeed** [canjs/can-stream#14]
This closes: https://github.com/canjs/canjs/issues/2927

https://github.com/Reactive-Extensions/RxJS#what-about-my-libraries

We need to be listed there as compatible to rx and also it will allow usage of rx inside of canjs projects

can-stream-rx should be created we can get some existing implamentation code from can-rx and also review that for updates inside of the canjs 2.x branches.

**Comment by marshallswain** [comment]
I don't know how similar the APIs are, but maybe we can make it so that you can pass a stream library to can-stream the same way that you do with [feathers-reactive](https://github.com/feathersjs/feathers-reactive).

```js
const feathers = require('feathers');
const reactive = require('feathers-reactive');
const RxJS = require('rxjs');

const app = feathers().configure(reactive(RxJS, options));
```

**Comment by chasenlehara** [comment]
That’d be pretty slick. You can see in [the code](https://github.com/canjs/can-stream/blob/master/can-stream.js) where we explicitly use Kefir’s APIs. We depend on some parts of how Kefir works, like [observables not subscribing to their sources until they have a listener](https://rpominov.github.io/kefir/#active-state), so I think we have to explicitly depend on the stream library.

**Comment by justinbmeyer** [comment]
Yeah, I think having separate packages is easier and more maintainable long term. 

Can/will explain more later, but think about different parts of the same app that might want different stream libraries. This is what 3.0 is all about.

**Comment by justinbmeyer** [comment]
Closing this issue but adding the `help wanted` label.  If someone wants to help, create a `can-stream-rx` repo just like this one, but uses rxjs.  

This is related: I'm going to close this issue

**Comment by web-mech** [comment]
https://github.com/web-mech/can-stream-rxjs

https://github.com/web-mech/can-define-stream-rxjs
